cidr_block = "10.0.0.0/16"
tags = {
  Name        = "example-vpc"
  Environment = "dev"
}
subnet_cidr_block          = "10.0.1.0/24"
availability_zone          = "us-west-2a"
security_group_name        = "example-sg"
security_group_description = "Example security group"
ec2_ami                    = "ami-abc123"
ec2_instance_type          = "t2.micro"
ec2_key_name               = "example-key"
rds_identifier             = "example-db"
rds_allocated_storage      = 20
rds_engine                 = "postgres"
rds_engine_version         = "14.3"
rds_instance_class         = "db.t2.micro"
rds_username               = "postgres"
rds_password               = "password123"
